### ISSUE TITLE
Ember 2.0 warning

### ISSUE THREAD

**Issue by rmachielse** [jerel/ember-cli-clock#2]
In Ember 1.13 I am getting the following warning:

```
DEPRECATION: In Ember 2.0 service factories must have an `isServiceFactory` property set to true.
You registered (unknown mixin) as a service factory. Either add the `isServiceFactory` property
to this factory or extend from Ember.Service.
```

Seems like `app/services/clock.js` should be extending `Ember.Service` instead of `Ember.Object`

**Comment by rmachielse** [comment]
Thanks for fixing that! Please note that it should now already be registered as `service:clock`. Also, there's no need to inject it in controllers or components anymore because it can be injected as a service where necessary now:

```javascript
export default Ember.Controller.extend({
  clock: Ember.inject.service()
});
```

Off course that requires users of this addon to upgrade

**Comment by jerel** [comment]
@rmachielse yeah, what we need is to release a v2 of the addon that uses a service everywhere. I've started on this branch https://github.com/jerel/ember-cli-clock/tree/upgrade and still need to upgrade Ember CLI
